spring:
  rabbitmq:
    host: locahost
    username: admin
    password: admin
    virtual-host: my_vhost
    port: 5672
    publisher-returns: true
    publisher-confirm-type:
  application:
    name: rabbit_boot_send
server:
  port: 9090
